name: publish

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          registry-url: "https://registry.npmjs.org"
      - name: Get new version
        run: |
          VERSION=${{ github.event.release.tag_name }}
          echo "VERSION=${VERSION:1}" >> $GITHUB_ENV
      - name: Install dependencies
        run: yarn install
      - name: Update package version
        run: |
          yarn version -i ${{ env.VERSION }}
      - name: Build package
        run: yarn build
      - name: Publish package
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
