name: Test
on: [push, pull_request, workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Install
        run: yarn install
      - name: Test and Coverage
        run: yarn coverage
      - name: Update Coverage Badge
        uses: we-cli/coverage-badge-action@main
